# Generated by Django 4.1.5 on 2025-07-13 09:11

import Home.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(help_text='Upload a PDF or DOCX resume file', upload_to='files', validators=[Home.models.validate_file_extension]),
        ),
    ]
