# Generated by Django 4.1.5 on 2025-07-13 09:15

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_file_uploaded_at_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(help_text='Upload a PDF resume file', upload_to='files', validators=[Home.models.validate_file_extension]),
        ),
    ]
